---
- become: yes
  hosts: all
  name: nginx install
  vars:
    root_group: root
    nginx_conf_path: /etc/nginx/conf.d
    nginx_conf_file_path: /etc/nginx/nginx.conf
    nginx_mime_file_path: /etc/nginx/mime.types
    nginx_pidfile: /run/nginx.pid
    nginx_vhost_path: /etc/nginx/sites-enabled
    nginx_default_vhost_path: /etc/nginx/sites-enabled/default
    __nginx_user: "www-data"

  tasks:
    - name: Update SO packages
      apt:
        update_cache: yes
  
    - name: Ensure nginx is installed.
      apt:
        name: "nginx"
        state: present

    - name: Define nginx_user.
      set_fact:
        nginx_user: "{{ __nginx_user }}"
      when: nginx_user is not defined

# Nginx setup.
  - name: Copy nginx configuration in place.
    template:
      src: "{{ nginx_conf_template }}"
      dest: "{{ nginx_conf_file_path }}"
      owner: root
      group: "{{ root_group }}"
      mode: 0644
    notify:
      - reload nginx

  - name: Ensure nginx service is running as configured.
    service:
      name: nginx
      state: "{{ nginx_service_state }}"
      enabled: "{{ nginx_service_enabled }}"

 handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: httpd
        state: restarted